[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = [ "pylsp", "ruff" ]

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "html"
